### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/skygear-SDK-Android#89]
### Expected behaviour

Give the user following error

`401 Unauthorized, trying to save record without login`

### Current behaviour

```
/com.skygeario.cloudservicesdemo E/Volley: [16286] BasicNetwork.performRequest: Unexpected response code 401 for https://xxx.skygeario.com/record/save
/com.skygeario.cloudservicesdemo I/Skygear Record Save: Fail to save: io.skygear.skygear.Error: write is not allowed
```

**Comment by cheungpat** [comment]
The recommended approach is this:

The http status code indicates whether the request is a success of failure. I recommend that SDK do not interpret the reason of the failure by looking up the status code in the HTTP RFC. The SDK should interpret the error code that is in the JSON response payload.

* 200-299 is treated as success
* 400-499 is treated as error
* 500-599 is treated as error (see caveats below)

Always check the error code in the JSON payload and perform relevant error handling by using the error code in the JSON payload.

Caveats: In the case of 500. The response payload may not be JSON. This is because HTTP request proxy may intercept the request and return other payload (such as HTML). Some special handling might be required here.

**Comment by b123400** [comment]
After looking that codes, I find the issue a bit inaccurate. The error message comes from [skygear-server](https://github.com/SkygearIO/skygear-server/blob/master/pkg/server/preprocessor/preprocessor.go#L150), not Android SDK. Android SDK just returns whatever it gets from the server, which is probably a better approach than error code, as it makes error message more accurate.

Since it comes from a generic preprocessor "RequireUser", returning a specific error message for each handler is not that straight forward. I suggest the server should simply reply a more user-friendly message "This action requires user authentication, please login.".

**Comment by cheungpat** [comment]
> Android SDK just returns whatever it gets from the server, which is probably a better approach than error code, as it makes error message more accurate.

While the error message from the server denote the actual problem that occurred, the error message is not good for end user to read. This is because,

1. The error message is not localizable.
2. The error message may contain too much technical details. 
3. The error message cannot be used to programmatically handle the error.

I think the pull request you made on the server repo with regard to this issue is good and should be merged, the better approach is for the client sdk to read the error code and handle the error by checking the error code. That includes showing an end user readable error message. Such error messages are available in the iOS repo.

If you believe that it is not customary to handle the error by following the aforementioned method, please let me know.

**Comment by cheungpat** [comment]
Also note that it was the consensus that the error message in the error object is intended for the developer, not the user. Most error returned adopted this practice.

**Comment by b123400** [comment]
I agree with all the points you mentioned. Are you expecting a function like [this](https://github.com/SkygearIO/skygear-SDK-iOS/blob/a0503d5e7cbb9c7964c0103e945ce5607ee1cb21/Pod/Classes/SKYError.m#L87) in the Android SDK?

**Comment by b123400** [comment]
Correct me if I am wrong, I cannot find any user-friendly translations except in iOS SDK. So this issue will involve adding user-friendly translations for Android, JS and Python SDK.

**Comment by cheungpat** [comment]
Forgot everything I say about translations/localizations (not that they are not important).

Consider just this: “The error message may contain too much technical details.” hence the SDK cannot simply return the error message (to the end-user).

I do not know what is happening with this issue without me actually looking at the code. I could get back to you tomorrow. If you are unsure what to do with this issue, consider this:

* the user is only expected to read user-friendly error message
* the developer does not want to write the user-friendly error message, and the developer expects the SDK to provide such error messages
* the SDK cannot just pass the error message obtained from the server to the developer’s code, because they are not user-friendly
* that means the SDK is required to return a user-friendly error message by looking up error code

If you think it is better to limit the scope of this issue to only the Android SDK, please do.

**Comment by b123400** [comment]
I think multiple platform is ok in this issue, but localisation is not. After reading about localisation in Android and JS I think it requires too much changes, will open another issue for that. Only handle user friendly error message in this issue

**Comment by cheungpat** [comment]
Sounds good to me
