### ISSUE TITLE
Why transientMap is Map<String, Object> not Map<String, Record>?

### ISSUE THREAD

**Issue by seventhmoon** [SkygearIO/skygear-SDK-Android#93]
In skygear-SDK-Android/skygear/src/main/java/io/skygear/skygear/Record.java
Why transientMap is Map<String, Object>? isn't only Record will be store?
Should it be Map<String, Record> instead?

**Comment by cheungpat** [comment]
No. This is because the transient map can also be used for [calculating distance](https://docs.skygear.io/android/reference/io/skygear/skygear/Query.html#transientIncludeDistance(java.lang.String,%20android.location.Location)).

App may also put application data in transient map. Transient map are not saved in the cloud db.
